### PR TITLE
Convert to a library

### PR DESCRIPTION
**Pull request by guysoft**
Moved all CLI code in to ``__name__ == "__main__"`` so this module can be imported.

It can be used now like this:

```python
from S20control import orviboS20

a = orviboS20()
power_socket = a.globaldiscover("255.255.255.255")[1]
address = power_socket["address"]
mac = ":".join("%x"%i for i in power_socket["detail"]["dstmac"])

print address, mac

a.poweron(address, mac)

```

### CODE REVIEW

**Comment by guysoft** [comment]
Now can also be installed.
```
sudo pip2 install https://github.com/guysoft/OrviboS20/archive/master.zip
```

And then you can do:
````
python2
>>> from S20control import orviboS20
````
And even

```
S20control globaldiscover 255.255.255.255
```

**Comment by glenpp** [comment]
Nice work!

I'll be looking to merge this in, but might be selective on ignores since at a glance it looks like some might not specific to this project. I lean towards minimalism where practical.

**Comment by guysoft** [comment]
Sure,
Please don't hesitate to comment directly if there is something that seems
like its too much, so I can explain. There were several changes to the
structure to accommodate ``setup.py``

**Comment by guysoft** [comment]
Hey, been a while
If you need me to change anything just say "I dont want X" or "change it to be like that", and I can modify my pull request to include changes.

**Comment by glenpp** [comment]
Apologies for the long radio silence - I've been bogged down with other priorities. I've tested the changes to the code and all seems to be working well, but haven't done more than quick updates elsewhere to point to my main repo etc. so there's a chance of things being a bit broken.

I'm not gong to get time soon to do much more, so I'll push the merge as-is shortly.

**Comment by guysoft** [comment]
Great! Thanks!

**Pull request merged**
